### ISSUE TITLE
Fix the god throw

### ISSUE THREAD

**Issue by NoviceLive** [LibreCrops/cdef#4]
# Description

All exceptions but the `E_PDB_FORMAT` will be handled as `PdbNotFoundException`.

Say, a god throw, which produces misleading messages.
# Code Location

Circa [Pdb.cs#L111](https://github.com/kbridge/PdbReader/blob/master/PdbReader/Pdb.cs#L111).
# Sample Output

```
E:\repo\PdbReader>PdbReader\bin\Debug\PdbReader.exe list c:\symbols\ntkrnlmp.pdb
\4A1E2990C0D94049AFEAEADA5768EAB31\ntkrnlmp.pdb
Retrieving the COM class factory for component with CLSID {B86AE24D-BF2F-4AC9-B5
A2-34B14E4CE11D} failed due to the following error: 80040154 Class not registere
d (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
PdbReader: file not found: c:\symbols\ntkrnlmp.pdb\4A1E2990C0D94049AFEAEADA5768E
AB31\ntkrnlmp.pdb
```
# Test Code

``` c#
catch (COMException ex)
            {
                if (ex.ErrorCode == ErrorCodes.E_PDB_FORMAT)
                {
                    throw new PdbFormatException();
                }
                else
                {
                    Console.WriteLine(ex.Message);
                    throw new PdbNotFoundException();
                }
            }
```

**Comment by kbridge** [comment]
Shouldn't the problem in the sample be caused by having not registered msdia120.dll? (any sample of other types?)

**Comment by kbridge** [comment]
See: https://msdn.microsoft.com/en-us/library/2008hf0e.aspx. Errors haven't been handled now is E_INVALIDARG and E_UNEXPECTED, which seem unlikely to rise.
